### ISSUE TITLE
Media buttons are unclickable

### ISSUE THREAD

**Issue by iamLazyCode** [tedhinklater/finality#64]
I am using a 2560x1600 laptop and the play buttons dont  work properly and are unclickable i cannot click in the position

![image](https://github.com/user-attachments/assets/8d530062-e334-4e3c-9c7c-c060b6fb6d86)

but when i zoom out of the page to about 40 50% then i can click the buttons

![image](https://github.com/user-attachments/assets/ebb37537-9a81-4e9c-bd01-383b2c1afc64)

**Comment by tedhinklater** [comment]
You seem to be getting the "4k" scaling for some reason, it's currently set to 2570+ but I'll change it to 3200+ so there's more wiggle room for cases like this.

**Comment by iamLazyCode** [comment]
> You seem to be getting the "4k" scaling for some reason, it's currently set to 2570+ but I'll change it to 3200+ so there's more wiggle room for cases like this.

thanks for update but still 

![image](https://github.com/user-attachments/assets/30138126-ac10-4bfa-a00f-a9f843c0935c)

i have to zoom out till 67% to be able to view and use

![image](https://github.com/user-attachments/assets/3d60650e-200b-46d2-b219-42066929fc78)

**Comment by tedhinklater** [comment]
Is your display scale set to 100% ?

**Comment by iamLazyCode** [comment]
> Is your display scale set to 100% ? in your OS's Display settings. Also try hitting F11

100% looks damn tiny 

![image](https://github.com/user-attachments/assets/4aad0552-9ef9-4585-a3bf-1b0ce67f9041)

lenovo settings recommends 

![image](https://github.com/user-attachments/assets/03097487-7ad7-4a82-991d-501395e05716)

**Comment by iamLazyCode** [comment]
> Is your display scale set to 100% ? in your OS's Display settings. Also try hitting F11

with recommended scaling it shows like this


![image](https://github.com/user-attachments/assets/7d82f7b2-a406-4e11-bd84-0886f04f8b52)

**Comment by framerunner** [comment]
I have the same issue with 1080p, changed browsers, tried different devices. Only my 1440p PC displays it correctly and lets me interact with the buttons.
Thus, nobody with a 1080p display can start movies.

**Comment by iamLazyCode** [comment]
> I have the same issue with 1080p, changed browsers, tried different devices. Only my 1440p PC displays it correctly and lets me interact with the buttons.
> Thus, nobody with a 1080p display can start movies.

Dnt know when dev will be fix it but try zooming out in browser and make zoom so small that the icons appear in middle of the screen then u can click it

**Comment by tedhinklater** [comment]
ok new idea for a [fix](https://github.com/tedhinklater/finality/commit/b5e8e9ea6da159a986ab7d03f0d5a511c1e6f126) has been uploaded

update should come through shortly, I would appreciate it if you can test this snippet for me on your device

```css
@media (max-height: 61em) {.layout-desktop .mainDetailButtons.focuscontainer-x {top: 2.5em;}}
.skinHeader {pointer-events: none;}
.headerButton,.headerTabs.sectionTabs {pointer-events: all;}
```

**Comment by tedhinklater** [comment]
Change to ```max-height: 100em``` if that doesn't work

**Comment by iamLazyCode** [comment]
> ok new idea for a [fix](https://github.com/tedhinklater/finality/commit/b5e8e9ea6da159a986ab7d03f0d5a511c1e6f126) has been uploaded
> 
> update should come through shortly, I would appreciate it if you can test this snippet for me on your device
> 
> ```css
> @media (max-height: 61em) {.layout-desktop .mainDetailButtons.focuscontainer-x {top: 2.5em;}}
> .skinHeader {pointer-events: none;}
> .headerButton,.headerTabs.sectionTabs {pointer-events: all;}
> ```
> 
> This moves the details page control buttons up to the header on shorter display heights. ![Screenshot 2024-12-08 094048](https://private-user-images.githubusercontent.com/66086488/393584298-46cf53f7-f4d5-4a3e-9a32-67cd49893aad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2NTM5MjcsIm5iZiI6MTczMzY1MzYyNywicGF0aCI6Ii82NjA4NjQ4OC8zOTM1ODQyOTgtNDZjZjUzZjctZjRkNS00YTNlLTlhMzItNjdjZDQ5ODkzYWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDEwMjcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5NjBjODg0MTFiZjc5ZjQ5YmRlZDI0ODg0MDYyZWY1MzQ1Yjk3YjdlNDkzYWQ1OWQzMjU0YmY1ODI2MDQ1NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ILv8VnAjKHNAoGtZk7ML2urxC3FkRnLS2zN6RHVc86w)

hello dev i can test but how shall i do it ?

**Comment by tedhinklater** [comment]
So if you're using the jsdelivr import line, it would look like this in your CSS box 

@import url("https://cdn.jsdelivr.net/gh/tedhinklater/finality@main/finality.css");
@media (max-height: 61em) {.layout-desktop .mainDetailButtons.focuscontainer-x {top: 2.5em;}}
.skinHeader {pointer-events: none;}
.headerButton,.headerTabs.sectionTabs {pointer-events: all;}

**Comment by iamLazyCode** [comment]
> @import url("https://cdn.jsdelivr.net/gh/tedhinklater/finality@main/finality.css");
> @media (max-height: 61em) {.layout-desktop .mainDetailButtons.focuscontainer-x {top: 2.5em;}}
> .skinHeader {pointer-events: none;}
> .headerButton,.headerTabs.sectionTabs {pointer-events: all;}

<img width="1277" alt="Screenshot_7" src="https://github.com/user-attachments/assets/7d772b56-7b64-483b-a83f-d1f010c7889a">
<img width="1279" alt="Screenshot_8" src="https://github.com/user-attachments/assets/2ab2cff1-bc34-42fc-a184-692dad022d59">

looks and functions much better now sir

**Comment by iamLazyCode** [comment]
> > @import url("https://cdn.jsdelivr.net/gh/tedhinklater/finality@main/finality.css");
> > @media (max-height: 61em) {.layout-desktop .mainDetailButtons.focuscontainer-x {top: 2.5em;}}
> > .skinHeader {pointer-events: none;}
> > .headerButton,.headerTabs.sectionTabs {pointer-events: all;}
> 
> <img alt="Screenshot_7" width="1277" src="https://private-user-images.githubusercontent.com/13099434/393589413-7d772b56-7b64-483b-a83f-d1f010c7889a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2NTU2NzEsIm5iZiI6MTczMzY1NTM3MSwicGF0aCI6Ii8xMzA5OTQzNC8zOTM1ODk0MTMtN2Q3NzJiNTYtN2I2NC00ODNiLWE4M2YtZDFmMDEwYzc4ODlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDEwNTYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzOTNhNjE1OWE5ODE1NTNkODdkYmQ0N2M1MWRhMTVmZDgxMGNlZWNiY2Y3NGFhNGNiMzdiMzIzOWI4YmZkM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2Uchpd7U_eWB4PCzo4bfTxv06Gy4VkNfp-O06egVm8I"> <img alt="Screenshot_8" width="1279" src="https://private-user-images.githubusercontent.com/13099434/393589424-2ab2cff1-bc34-42fc-a184-692dad022d59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2NTU2NzEsIm5iZiI6MTczMzY1NTM3MSwicGF0aCI6Ii8xMzA5OTQzNC8zOTM1ODk0MjQtMmFiMmNmZjEtYmMzNC00MmZjLWExODQtNjkyZGFkMDIyZDU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDEwNTYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwZDFkZjk4ZGFhOGU5ZDI3ZjlkZWJiZWZjMTk1N2RhMTQxMTFhYjUwYjBmNzc1ZWJkMGUyMWYzYzNmYzFhY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yYh21j0C4Ih21jgMZl5FPDKBQuD3jRDcNB41bqYZlxA">
> looks and functions much better now sir

one question sir is it possible or can i manually change the hegith here 
![image](https://github.com/user-attachments/assets/852bc2b6-8e85-49d1-b660-f270423461e0)

**Comment by tedhinklater** [comment]
Also fixed the cut-off cast and the overlap with the imdb/tvdb links

![Screenshot 2024-12-08 112033](https://github.com/user-attachments/assets/9a7f3c3e-8037-4dd2-b6fb-5d31651e4c32)

If you kindly change your css box to this:


```css
@import url("https://cdn.jsdelivr.net/gh/tedhinklater/finality@main/finality.css");
@media (max-height: 61em) {.layout-desktop .mainDetailButtons.focuscontainer-x {top: 2.5em;left: 26em;}.layout-desktop #similarCollapsible .scrollSlider.focuscontainer-x.itemsContainer.similarContent.animatedScrollX {max-height: calc(100vh - 11.5em);}}
@media (max-width: 112em) {.layout-desktop .verticalSection.detailVerticalSection.emby-scroller-container {width: 67em;}.layout-desktop #castCollapsible .emby-scrollbuttons-button.paper-icon-button-light {padding-left: 34.5em;padding-right: 34.5em;}}
.skinHeader {pointer-events: none;}.headerButton,.headerTabs.sectionTabs {pointer-events: all;}

**Comment by iamLazyCode** [comment]
> Also fixed the cut-off cast and the overlap with the imdb/tvdb links
> 
> ![Screenshot 2024-12-08 112033](https://private-user-images.githubusercontent.com/66086488/393591171-9a7f3c3e-8037-4dd2-b6fb-5d31651e4c32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2NTc5NzAsIm5iZiI6MTczMzY1NzY3MCwicGF0aCI6Ii82NjA4NjQ4OC8zOTM1OTExNzEtOWE3ZjNjM2UtODAzNy00ZGQyLWI2ZmItNWQzMTY1MWU0YzMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDExMzQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2YmY2YjBkZTgwYTRlZWE4NjNkNmQwZDg2ZDNjZGIyNjFlNmJmY2NmYmE4Mjg1YWIwZjE0NTNjM2Y2NDlkNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7Gr190jMoyel0qegkps3aJM8ooJ_DOb_2NW1_QILFFg)
> 
> If you kindly change your css box to this:
> 
> ```css
> @import url("https://cdn.jsdelivr.net/gh/tedhinklater/finality@main/finality.css");
> @media (max-height: 61em) {.layout-desktop .mainDetailButtons.focuscontainer-x {top: 2.5em;left: 26em;}.layout-desktop #similarCollapsible .scrollSlider.focuscontainer-x.itemsContainer.similarContent.animatedScrollX {max-height: calc(100vh - 11.5em);}.alphaPicker-fixed {bottom: max(env(safe-area-inset-bottom),0em);}}
> @media (max-width: 112em) {.layout-desktop .verticalSection.detailVerticalSection.emby-scroller-container {width: 67em;}
> .layout-desktop #castCollapsible .emby-scrollbuttons-button.paper-icon-button-light {padding-left: 34.5em;padding-right: 34.5em;}.layout-desktop #childrenContent .listItemBodyText.secondary.listItem-overview.listItemBodyText {max-width: 39em;}.sectionTabs {top: 2em !important;position: absolute;}}
> .skinHeader {pointer-events: none;}
> .headerButton,.headerTabs.sectionTabs {pointer-events: all;}
> ```
> 
> edit: added other fixes

sadly sir nothing seems changed

![image](https://github.com/user-attachments/assets/6a2939c2-d1b9-441f-8dfc-8a0a5ddce452)

**Comment by tedhinklater** [comment]
I moved it to the left, so it didn't overlap with the IMDb links, but if you want the length changed:

```css
@import url("https://cdn.jsdelivr.net/gh/tedhinklater/finality@main/finality.css");
@media (max-height: 61em) {.layout-desktop .mainDetailButtons.focuscontainer-x {top: 2.5em;left: 26em;width: 28.5em;}.layout-desktop #similarCollapsible .scrollSlider.focuscontainer-x.itemsContainer.similarContent.animatedScrollX {max-height: calc(100vh - 11.5em);}.alphaPicker-fixed {bottom: max(env(safe-area-inset-bottom),0em);}}
@media (max-width: 112em) {.layout-desktop .verticalSection.detailVerticalSection.emby-scroller-container {width: 67em;}
.layout-desktop #castCollapsible .emby-scrollbuttons-button.paper-icon-button-light {padding-left: 34.5em;padding-right: 34.5em;}.layout-desktop #childrenContent .listItemBodyText.secondary.listItem-overview.listItemBodyText {max-width: 39em;}.sectionTabs {top: 2em !important;position: absolute;}}
.skinHeader, .tabs-viewmenubar.emby-tabs.focusable.scrollX {pointer-events: none;}
.headerButton,.emby-tab-button {pointer-events: all;}
```

![Screenshot 2024-12-08 113954](https://github.com/user-attachments/assets/763eaf13-94e6-4c2a-8b5a-926f96c9fdac)

**Comment by iamLazyCode** [comment]
moving this down fix probably fix another issue i know i just being an @$$ right now and picking but u can skip this all together sir
if in case we snap jellyfin window

normal view
![image](https://github.com/user-attachments/assets/f1683726-884c-458a-a9f9-1c0eeed84ccc)

if snapped

![image](https://github.com/user-attachments/assets/2a2199c2-7f89-4a9d-bc7f-99d59f3ea8ef)

**Comment by tedhinklater** [comment]
It's absolutely no problem, 

Fixed those other bugs

```css
@import url("https://cdn.jsdelivr.net/gh/tedhinklater/finality@main/finality.css");
@media (max-height: 61em) {.layout-desktop .mainDetailButtons.focuscontainer-x {top: 2.5em;left: 26em;}
.layout-desktop #similarCollapsible .scrollSlider.focuscontainer-x.itemsContainer.similarContent.animatedScrollX {max-height: calc(100vh - 11.5em);}.alphaPicker-fixed {bottom: max(env(safe-area-inset-bottom),0em);}}
@media (max-width: 112em) {.layout-desktop .verticalSection.detailVerticalSection.emby-scroller-container {width: 67em;}.layout-desktop #castCollapsible .emby-scrollbuttons-button.paper-icon-button-light {padding-left: 34.5em;padding-right: 34.5em;}.layout-desktop #childrenContent .listItemBodyText.secondary.listItem-overview.listItemBodyText {max-width: 39em;}.sectionTabs {top: 2em !important;position: absolute;}}
.skinHeader, .tabs-viewmenubar.emby-tabs.focusable.scrollX {pointer-events: none;}
.headerButton,.emby-tab-button {pointer-events: all;}
@media (min-width: 72em) and (max-width: 90em) {.layout-desktop body, .layout-desktop .detailsGroupItem.genresGroup, .layout-desktop .itemExternalLinks.focuscontainer-x, .layout-desktop .itemMiscInfo {font-size: 80% !important;}.layout-desktop #castCollapsible .cardText-first {font-size: 95%;}.layout-desktop .detailsGroupItem.genresGroup {font-size: 100% !important;}.layout-desktop .itemMiscInfo {font-size: 120% !important;}.layout-desktop .detailLogo {left: 25vw;}}
@media (max-width: 72em) {.layout-desktop body, .layout-desktop .itemExternalLinks.focuscontainer-x {font-size: 60% !important;}
.layout-desktop .detailsGroupItem.genresGroup {font-size: 80% !important;top: 4.5em !important;}
.layout-desktop #castCollapsible .cardText-first {font-size: 95% !important;}.layout-desktop .itemMiscInfo {font-size: 120% !important;}.layout-desktop .detailLogo {left: 25vw;}}
```
