### ISSUE TITLE
Strange behavior of the home and favorites buttons, as shown in the screenshot below.

### ISSUE THREAD

**Issue by Isaiasgamedev** [tedhinklater/finality#70]
As can be seen in the screenshots, the buttons disappear inside the browser HAHAHA. I believe it's just a positioning issue, but I want to say upfront that this is one of the most beautiful themes with the best UX of all.

![image](https://github.com/user-attachments/assets/bc1a2003-b27b-4ec3-9b4d-3759eab0895f)
![image](https://github.com/user-attachments/assets/98c9b230-8cad-45a3-a6bd-27286b5f890b)

It would be even better if the display for anime/shows/series with episodes worked like this: simply clicking on the series would take you to a page showing the seasons as text, along with their respective episodes. Navigating through page after page for each season just to figure out where you left off is such a hassle with the current Jellyfin standard.

Additionally, having two top 10 bars—for the most-watched movies of the week and the most-watched series of the week—would make this theme perfect. Just some suggestions; it's already beautiful as it is!

![image](https://github.com/user-attachments/assets/e7f39a4c-bf75-4aae-8186-6dec0dff4ae6)
![image](https://github.com/user-attachments/assets/4edde7e4-d391-427f-8f13-028e6df0889e)

**Comment by tedhinklater** [comment]
It looks like you forgot to add this to the end of your CSS

```css

.layout-desktop .page.homePage.libraryPage.allLibraryPage.backdropPage.pageWithAbsoluteTabs.withTabs.mainAnimatedPage { margin-top:-4.5em;}
.layout-desktop .overflowBackdropCard, .overflowSmallBackdropCard {  width: 12.7vw !important;  padding-right: 1.85em;}
.layout-desktop .skinHeader-withBackground {background-color: transparent; backdrop-filter: blur(0px);}
.layout-desktop #homeTab .section0 .sectionTitle.sectionTitle-cards.padded-left {  display: none !important;}
.layout-desktop #homeTab .verticalSection.section1.emby-scroller-container {  position: relative;  top: -27em;  left: 73em; width: 29vw; margin-bottom: -17em;}
.layout-desktop #homeTab .verticalSection.section2.emby-scroller-container::after { content: ''; position: fixed; top: 0; left: 0; width: 100%; height: 100vw; background: black; z-index: -1;}
[dir="ltr"] #homeTab .verticalSection.section0.emby-scroller-container .emby-scrollbuttons {right: -5em; top: -2em;}
.layout-desktop #homeTab .verticalSection.section0 .cardText-first {display: none !important;}
.layout-desktop #homeTab .sections.homeSectionsContainer { margin-top: 2em;}
.layout-desktop .sectionTitle.sectionTitle-cards.padded-left + .itemsContainer { margin-bottom: 2em;}

```

**Comment by Isaiasgamedev** [comment]
My screen 

![image](https://github.com/user-attachments/assets/8456c369-fda6-46fb-b0b1-6317baba46b0)

and dont work here put there

**Comment by tedhinklater** [comment]
the header tab position is [fixed](https://github.com/tedhinklater/finality/commit/3988881f77bc6c1e44aa2f1f7927e68b239675da), the update will come through shortly

in the meantime, to apply the fix manually use this CSS

```css

@import url("https://cdn.jsdelivr.net/gh/tedhinklater/finality@main/finality.css");
@media (max-width: 112em) {.sectionTabs {top: 5em !important;}}
@media (max-width: 100em) {.sectionTabs {top: 1em !important;}}
@media (max-width: 63em) {.sectionTabs {top: 2em !important;}}
```

and if you're using the fullscreen version of the Featured Content Bar, also add this CSS at the end

```css

.layout-desktop .page.homePage.libraryPage.allLibraryPage.backdropPage.pageWithAbsoluteTabs.withTabs.mainAnimatedPage { margin-top:-4.5em;}
.layout-desktop .overflowBackdropCard, .overflowSmallBackdropCard {  width: 12.7vw !important;  padding-right: 1.85em;}
.layout-desktop .skinHeader-withBackground {background-color: transparent; backdrop-filter: blur(0px);}
.layout-desktop #homeTab .section0 .sectionTitle.sectionTitle-cards.padded-left {  display: none !important;}
.layout-desktop #homeTab .verticalSection.section1.emby-scroller-container {  position: relative;  top: -27em;  left: 73em; width: 29vw; margin-bottom: -17em;}
.layout-desktop #homeTab .verticalSection.section2.emby-scroller-container::after { content: ''; position: fixed; top: 0; left: 0; width: 100%; height: 100vw; background: black; z-index: -1;}
[dir="ltr"] #homeTab .verticalSection.section0.emby-scroller-container .emby-scrollbuttons {right: -5em; top: -2em;}
.layout-desktop #homeTab .verticalSection.section0 .cardText-first {display: none !important;}
.layout-desktop #homeTab .sections.homeSectionsContainer { margin-top: 2em;}
.layout-desktop .sectionTitle.sectionTitle-cards.padded-left + .itemsContainer { margin-bottom: 2em;}
```
